version: "3"

services:
  nginx:
    image: andrewnk/alpine-nginx-modsec
    container_name: nginx
    ports:
      - 80:80
    networks:
      - web
    volumes:
      - ./apps/usr-share-nginx-html:/usr/share/nginx/html
      - ./conf/owasp-modsecurity-crs:/usr/local/owasp-modsecurity-crs
      - ./conf/modsec:/etc/nginx/modsec

  php:
    image: andrewnk/base-alpine-php
    container_name: php
    networks:
      - web
    volumes:
      - ./apps/usr-share-nginx-html:/var/www/html

volumes:
  app:

networks:
  web:
